{
 "title": "Nasa PHO",
 "description": "Tracking all the Asteroids",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center; font-family:Arial, sans-serif; font-size:28px; font-weight:bold; color:#647FBC; margin:20px 0;\">\n  NASA Near-Earth Object (NEO) Hazard Monitoring Dashboard\n</h1>\n"
   }
  },
  { "title": "Asteroids Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Logged Asteroids",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "neondb", "rawSql": "select count(*) from train_neo" }
   ]
  },
  {
   "title": "Sentry Object Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select count(*) from train_neo where is_sentry_object  = True;"
    }
   ]
  },
  {
   "title": "Potentially Hazardous",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select count(*) from train_neo where is_potentially_hazardous = True;"
    }
   ]
  },
  {
   "title": "Asteroid Average Diameter Range ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "with diameter_range_tb as (\r\n\t\tselect (max_diameter_km - min_diameter_km) as diameter_range\r\n\t\tfrom train_neo\r\n) \r\nselect avg(diameter_range) as average_diameter_range from diameter_range_tb;"
    }
   ]
  },
  {
   "title": "Closest Miss Distance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select min(miss_distance_km) as minimum_missed_distance  from train_neo;"
    }
   ]
  },
  {
   "title": "Fastest Velocity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select max(relative_velocity_kps) as fastest_velocity from train_neo;"
    }
   ]
  },
  {
   "title": "Weekly New Approaches",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "WITH neo_window AS (\r\n  SELECT *\r\n  FROM train_neo\r\n  WHERE close_approach_date::date\r\n        BETWEEN  CURRENT_DATE - INTERVAL '7 days' AND CURRENT_DATE \r\n),\r\nstats AS (\r\n  SELECT\r\n    AVG(relative_velocity_kps) AS avg_velocity,\r\n    AVG(miss_distance_km)      AS avg_distance\r\n  FROM neo_window\r\n)\r\nSELECT\r\n  n.name,\r\n  n.close_approach_date,\r\n  n.relative_velocity_kps,\r\n  n.miss_distance_km,\r\n  n.is_potentially_hazardous,\r\n  CASE\r\n    WHEN n.is_potentially_hazardous = true\r\n     AND n.relative_velocity_kps > s.avg_velocity\r\n     AND n.miss_distance_km > s.avg_distance\r\n    THEN true\r\n    ELSE false\r\n  END AS highlight\r\nFROM neo_window n\r\nCROSS JOIN stats s\r\nORDER BY n.close_approach_date desc;"
    }
   ]
  },
  {
   "title": "Weekly PHO and NPHO",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT\r\n  close_approach_date::date AS time,\r\n  SUM(CASE WHEN is_potentially_hazardous = true THEN 1 ELSE 0 END) AS hazardous_count,\r\n  SUM(CASE WHEN is_potentially_hazardous = false THEN 1 ELSE 0 END) AS nonhazardous_count\r\nFROM train_neo\r\nWHERE close_approach_date::date\r\n      BETWEEN CURRENT_DATE - INTERVAL '7 days' AND CURRENT_DATE\r\nGROUP BY close_approach_date::date\r\nORDER BY close_approach_date::date;\r\n"
    }
   ]
  },
  {
   "title": "Monthly Asteroids Counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT close_approach_date::date as approach_date,\r\n       COUNT(id) as daily_count\r\nFROM train_neo \r\nWHERE close_approach_date::date >= CURRENT_DATE - INTERVAL '30 days'\r\n  AND close_approach_date::date <= CURRENT_DATE\r\nGROUP BY close_approach_date::date\r\nORDER BY approach_date;"
    }
   ]
  },
  {
   "title": "Monthly Closest Miss Distance vs Velocity (Colored by Hazardous)",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \r\n    miss_distance_km,\r\n    relative_velocity_kps,\r\n    CASE \r\n        WHEN is_potentially_hazardous = true THEN 1\r\n        ELSE 0\r\n    END AS hazardous_flag\r\nFROM train_neo \r\nWHERE close_approach_date::date \r\n      BETWEEN current_date - interval '30 days' AND current_date;\r\n"
    }
   ]
  },
  {
   "title": "Number of PHOs and Non-PHOs Over Year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \r\n    DATE_TRUNC('year', close_approach_date::date) AS time,\r\n    SUM(CASE WHEN is_potentially_hazardous = true THEN 1 ELSE 0 END) AS hazardous_asteroids,\r\n    SUM(CASE WHEN is_potentially_hazardous = false THEN 1 ELSE 0 END) AS non_hazardous_asteroids\r\nFROM train_neo\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Yearly Average Miss Distance Trend",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT DATE_PART('year', close_approach_date::date) AS year,\r\n       AVG(miss_distance_km) AS avg_miss_distance\r\nFROM train_neo\r\nGROUP BY year\r\nORDER BY year;\r\n"
    }
   ]
  },
  {
   "title": "Monthly Max Relative Velocity for Current Year",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select \r\n\t\tdistinct(extract(month from close_approach_date::date)) as month,\r\n\t\tmax(relative_velocity_kps) as max_rel_vel_captured\r\nfrom train_neo\r\nwhere extract(year from close_approach_date::date) = extract(year from current_date)\r\ngroup by month;"
    }
   ]
  },
  {
   "title": "Monthly Minimum Miss Distance over Current Year",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select \r\n\t\tdistinct(extract(month from close_approach_date::date)) as month,\r\n\t\tmin(miss_distance_km) as max_rel_vel_captured\r\nfrom train_neo\r\nwhere extract(year from close_approach_date::date) = extract(year from current_date)\r\ngroup by month;"
    }
   ]
  },
  {
   "title": "Current Week Prediction Probability",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select \r\n\ttn.name,\r\n\ttn.close_approach_date,\r\n\tpt.probability_being_falsely_hazardous as false_probability,\r\n\tpt.probability_being_truely_hazardous as true_probability\r\nfrom prediction_table pt\r\njoin train_neo tn on tn.id = pt.id::bigint\r\nwhere tn.close_approach_date::date between current_date - interval '7 days' and current_date\r\norder by tn.close_approach_date desc\r\nlimit 20;"
    }
   ]
  },
  { "title": "Model Metrics Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Latest Model Training Date",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select training_date from model_training_logs order by training_date desc limit 1;"
    }
   ]
  },
  {
   "title": "Latest Model Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "WITH last_model_trained_date AS (\r\n  SELECT training_date  \r\n  FROM model_training_logs \r\n  ORDER BY training_date DESC \r\n  LIMIT 1\r\n)\r\nSELECT \r\n  COUNT(*) FILTER (WHERE pt.actual = pt.model_prediction) AS correct_predictions,\r\n  COUNT(*) AS total_predictions,\r\n  ROUND(\r\n    100.0 * COUNT(*) FILTER (WHERE pt.actual = pt.model_prediction) / COUNT(*), \r\n    2\r\n  ) AS accuracy_percent\r\nFROM prediction_table pt\r\nJOIN last_model_trained_date lmtd \r\n  ON pt.trained_model_date_used = lmtd.training_date;"
    }
   ]
  },
  {
   "title": "Model Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select model_name from model_training_logs order by training_date desc limit 1;"
    }
   ]
  },
  {
   "title": "Model Metrics",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \r\n    recall * 100 AS recall_pct,\r\n    accuracy * 100 AS accuracy_pct,\r\n    f1_score * 100 AS f1_score_pct,\r\n    precision * 100 AS precision_pct\r\nFROM model_training_logs\r\nORDER BY training_date DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  { "title": "Data Drift Detection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Last Drift Detected",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "select created_at from neo_data_drift order by  created_at desc limit 1;"
    }
   ]
  },
  {
   "title": "Drift Detection",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 67 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "WITH last_recorded_drift AS (\r\n    SELECT created_at \r\n    FROM neo_data_drift\r\n    ORDER BY created_at DESC\r\n    LIMIT 1\r\n)\r\nSELECT \r\n    feature,\r\n    drift_status,\r\n    CASE \r\n        WHEN drift_status = 'No Drift' THEN 0\r\n        WHEN drift_status = 'Moderate Drift' THEN 1\r\n        WHEN drift_status = 'High Drift' THEN 2\r\n    END AS drift_level\r\nFROM neo_data_drift\r\nWHERE created_at = (SELECT created_at FROM last_recorded_drift);\r\n"
    }
   ]
  },
  {
   "title": "Feature-Type-Drift-Method",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 76 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "with last_recorded_drift as (\r\n\tselect created_at from neo_data_drift\r\n\torder by  created_at desc\r\n\tlimit 1\r\n)\r\nselect \r\n\tfeature, \r\n\tfeature_type,\r\n\tmethod\r\nfrom neo_data_drift \r\nwhere created_at = (select created_at from last_recorded_drift);"
    }
   ]
  },
  {
   "title": "Population Stability Index",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "WITH last_recorded_drift AS (\r\n    SELECT created_at \r\n    FROM neo_data_drift\r\n    ORDER BY created_at DESC\r\n    LIMIT 1\r\n)\r\nSELECT \r\n    feature,\r\n    ROUND(psi::numeric, 4) AS psi\r\nFROM neo_data_drift\r\nWHERE created_at = (SELECT created_at FROM last_recorded_drift)\r\nORDER BY psi DESC;\r\n"
    }
   ]
  }
 ]
}