name: Fetch and Append Nasa NEO Data

on:
  schedule:
    - cron: '0 0 * * 1'  

  workflow_dispatch:

jobs:
  nasa-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Weekly Nasa Neo Data append script
        env:
          CONNECTION_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python -m pusher.weekly_data_pusher